title: Ambient Light Sensor Data and Collector Android Applicatin (conducted for LuxTrack project)
description: 1000+ 30-second ALS time series recorded via Samsung Galaxy A72 from the screen projection of a laptop while one in 10 users browsed one of the 8 specified websites on the laptop.

publisher_text: Please don't forget to cite our LuxTrack paper if you use the data or application.
publisher_url: https://scholar.google.com/citations?user=z3WyuUYAAAAJ&hl=en

license_text: 
license_url: 

frequency: 

certificate_embed: 
